openapi: 3.1.0
info:
  title: API de Consultas Médicas
  version: 1.0.0

paths:
  /reservas:
    get:
      summary: Lista todas as reservas
      responses:
        '200':
          description: Lista de reservas
    post:
      summary: Cria uma nova reserva
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/reserva'
      responses:
        '201':
          description: Reserva criada com sucesso
    options:
      summary: Lista métodos permitidos
      responses:
        '200':
          description: Métodos permitidos
          headers:
            Allow:
              schema:
                type: string
                example: GET,POST,PUT,PATCH,DELETE,OPTIONS,HEAD

  /reservas/{id}:
    get:
      summary: Retorna uma reserva pelo ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Reserva encontrada
        '404':
          description: Reserva não encontrada

    put:
      summary: Substitui uma reserva existente
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/reserva'
      responses:
        '200':
          description: Consulta atualizada
        '404':
          description: Consulta não encontrada

    patch:
      summary: Atualiza parcialmente uma reserva
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                medico:
                  type: string
                data:
                  type: string
                  format: date-time
      responses:
        '200':
          description: Reserva atualizada parcialmente
        '404':
          description: Reserva não encontrada

    delete:
      summary: Remove uma reserva
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Reserva removida com sucesso
        '404':
          description: Reserva não encontrada

    head:
      summary: Verifica existência da reserva (sem corpo)
      parameters:
        - in: path
          name: id
          required: true
          schema:1
            type: integer
      responses:
        '200':
          description: Reserva existe
        '404':
          description: Reserva não encontrada

components:
  schemas:
    reserva:
      type: object
      required:
        - reservaId
        - spaceId
        - costumerId
        - start_date
        - end_date
        - status
        - status_payment
        - total_amount
      properties:
        reservaId:
          type: integer
          example: 1
        spaceId:
          type: integer
        costumerId:
          type: integer
        start_date:
          type: string
        end_date:
          type: string
        status:
          type: integer
        status_payment:
          type: integer
        total_amount:
          type: number
        created_at:
          type: string
        data:
          type: string
          format: date-time
          example: 2025-09-25T14:00:00
